/**
 * MOH Office Controller
 * Handles MOH Doctor office overview and hierarchical data retrieval.
 */

const mongoose = require("mongoose");
const MohOffice = require("../models/MohOffice");
const { ClinicArea } = require("../models/ClinicArea");

/**
 * GET /api/moh/my-office
 * Returns the doctor's assigned MOH office, its clinic areas, and associated staff.
 * Uses a single MongoDB aggregation pipeline with $lookup.
 *
 * Query params:
 *   includeInactive: "true" | "false" (default: false)
 */
async function getMyOffice(req, res) {
  try {
    const mohOfficeId = req.user?.mohOfficeId;
    if (!mohOfficeId) {
      return res.status(409).json({
        message: "No MOH office assigned to this account",
      });
    }

    const office = await MohOffice.findById(mohOfficeId);
    if (!office) {
      return res.status(404).json({
        message: "MOH office not found",
      });
    }

    const includeInactive = req.query.includeInactive === "true";

    // Build aggregation pipeline on ClinicArea
    const matchStage = {
      mohOfficeId: new mongoose.Types.ObjectId(mohOfficeId.toString()),
    };
    if (!includeInactive) {
      matchStage.status = "active";
    }

    const staffMatchExpr = [
      { $eq: ["$clinicAreaId", "$$caId"] },
    ];
    if (!includeInactive) {
      staffMatchExpr.push({ $eq: ["$status", "active"] });
    }

    const clinicAreasWithStaff = await ClinicArea.aggregate([
      { $match: matchStage },
      { $sort: { name: 1 } },
      {
        $lookup: {
          from: "staffs", // Collection name generated by Mongoose for Staff
          let: { caId: "$_id" },
          pipeline: [
            {
              $match: {
                $expr: {
                  $and: staffMatchExpr,
                },
              },
            },
            { $sort: { fullName: 1 } },
            {
              $project: {
                _id: 1,
                fullName: 1,
                role: 1,
                phone: 1,
                status: 1,
              },
            },
          ],
          as: "staffList",
        },
      },
    ]);

    let phmCount = 0;
    let nursingOfficersCount = 0;
    let clinicStaffCount = 0;

    const formattedClinicAreas = clinicAreasWithStaff.map((ca) => {
      const formattedStaff = (ca.staffList || []).map((s) => {
        const roleUpper = String(s.role || "").toUpperCase();
        if (roleUpper === "PHM") {
          phmCount++;
        } else if (roleUpper === "NURSING_OFFICER" || roleUpper.includes("NURS")) {
          nursingOfficersCount++;
        } else if (roleUpper === "CLINIC_STAFF" || roleUpper.includes("CLINIC")) {
          clinicStaffCount++;
        }

        return {
          id: s._id.toString(),
          fullName: s.fullName,
          role: s.role,
          phone: s.phone,
          status: s.status,
        };
      });

      return {
        id: ca._id.toString(),
        name: ca.name,
        type: ca.type,
        address: ca.address || "",
        status: ca.status,
        staff: formattedStaff,
      };
    });

    return res.status(200).json({
      mohOffice: {
        id: office._id.toString(),
        name: office.name,
        district: office.district,
        province: office.province,
      },
      clinicAreas: formattedClinicAreas,
      totals: {
        clinicAreas: formattedClinicAreas.length,
        phm: phmCount,
        nursingOfficers: nursingOfficersCount,
        clinicStaff: clinicStaffCount,
      },
    });
  } catch (error) {
    console.error("❌ Error in getMyOffice controller:", error);
    return res.status(500).json({
      message: "An error occurred while fetching MOH office details",
    });
  }
}

module.exports = {
  getMyOffice,
};
